backend:
  name: github
  repo: martin17muiruri-pixel/vapers-city
  branch: main

site_url: https://martin17muiruri-pixel.github.io/vapers-city

collections:
  - name: "products"
    label: "Products"
    folder: "data/products"
    create: true
    fields:
      - { name: "name", label: "Name", widget: "string" }
      - { name: "price", label: "Price", widget: "string" }
      - { name: "flavor", label: "Flavor", widget: "string" }
